const fields = {
  spineTextarea: document.querySelector(".spineTextarea"),
  emitterTextarea: document.querySelector(".emitterTextarea"),
  imageTextarea: document.querySelector(".imageTextarea"),
  framerate: document.querySelector("#framerate"),
  openSidebar: document.querySelector(".openSidebar"),
  closeSidebar: document.querySelector(".closeSidebar"),
  prettyBtn: document.querySelector("#prettyBtn"),
  invalidJson: document.querySelector(".invalidJson"),
  sidebar: document.querySelector("#sidebar"),
  main: document.querySelector("#main"),
  bigwinName: document.querySelector(".bigwinName"),
  bigwinType: document.querySelector(".bigwinType"),
  bigwinDuration: document.querySelector(".bigwinDuration"),
  file: document.querySelector("#file"),
  loader: document.querySelector(".loader"),
  deleteParameter: document.querySelectorAll(".deleteParameter"),
  addParameter: document.querySelector(".addParameter"),
  alphaPopup: document.querySelector(".alphaPopup"),
  speedPopup: document.querySelector(".speedPopup"),
  scalePopup: document.querySelector(".scalePopup"),
  speedTable: document.querySelector(".speedTable"),
  scaleTable: document.querySelector(".scaleTable"),
  alphaTable: document.querySelector(".alphaTable"),
  alphaTime: document.querySelector(".alphaTime"),
  particleControls: document.querySelector(".particleControls"),
  minimumScaleMultiplier: document.querySelector(".minimumScaleMultiplier"),
  minimumSpeedMultiplier: document.querySelector(".minimumSpeedMultiplier"),
  isStepped: document.querySelector(".isStepped"),
};

export default fields;
